### ISSUE TITLE
extracted *.ies files

### ISSUE THREAD

**Issue by pedrobullo** [r1emu/IPFUnpacker#2]
Just realised they are converted to CSV structure automatically.
Is possible to text columns be enclosed by " ?
Also can you add .csv extension to extracted files?

Awesome updates o/

**Comment by Spl3en** [comment]
Hey,

I think we should keep the original filenames in case of someone want to build a "IPFPacker" on top of this.

About the text columns, you can change [this](https://github.com/r1emu/IPFUnpacker/blob/master/src/ipf_unpack/ipf_unpack.c#L111) line and put `"\"%s\""` instead of `"%s"`. Let me know if that fixes your issue.
